likelion_11th_B_sangjunlee_homework/accounts/urls.py
from django.urls import path
from .views import *
app_name = "accounts"
urlpatterns = [
    path('login/', login,name="login"),
    path('logout/', logout,name="logout"),
    path('signup/',signup,name="signup"),
]

likelion_11th_B_sangjunlee_homework/likelion_11th_B_sangjunlee_homework/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likelion_11th_B_sangjunlee_homework/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('second/', secondpage, name="secondpage"),
    # app의 views.py에서 넘어옴
    # 새로 만든 views.py의 new함수와 create 함수 연결 (url만들기)
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    # mainpage.html detail부분에서 넘어옴
    # url에 post의 id 값을 넣어서 전달 -> 전달받은 id값을 통해 특정 게시글의 detail 띄우기
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name = "edit"),
    path('update/<int:id>', update, name = "update"),
    path('delete/<int:id>', delete, name = "delete"),
    path('pic_delete/<int:id>', pic_delete, name = "pic_delete"),
    path('delete_comment/<int:id>/<int:com_id>', delete_comment, name="delete_comment"),
    path('likes/<int:post_id>', likes, name="likes"),

]

likelion_11th_B_sangjunlee_homework/users/urls.py
from django.urls import path
from .views import *
app_name = "users"
urlpatterns = [
    path('mypage/<int:id>', mypage,name="mypage"),
    path('follow/<int:id>', follow, name="follow"),
]

likelion_11th_B_sangjunlee_homework/likelion_11th_B_sangjunlee_homework/templates/shared/_navbar.html
<!-- html에서 navbar 부분 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid" style="background-color: #e3f2fd;">
        <!-- mainpage 링크 연결 -->
        <a class="navbar-brand" href="{% url 'main:mainpage' %}">안녕하세요 이상준입니다.</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item">
                <!-- secondpage 링크 연결 -->
                <a class="nav-link active" aria-current="page" href="{% url 'main:secondpage' %}">우리 조를 소개합니다</a>
            </li>
            </ul>
        </div>
    </div>
    <li class="nav-item dropdown">
        {% if user.is_authenticated %}
        <!--로그인시 보이는 화면-->
        {% if request.user != user %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{request.user.username}}
            </a>
        {% else %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{user.username}}
            </a>         
        {% endif %}

        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">로그아웃</a></li>
        {% if request.user != user %}
            <li><a class="dropdown-item" href="{% url 'users:mypage' request.user.id %}">mypage</a></li>
        {% else %}
            <li><a class="dropdown-item" href="{% url 'users:mypage' user.id %}">mypage</a></li>            
        {% endif %}
        </ul>

    
        {% else %}

        <!--로그아웃시 보이는 화면-->
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            LOGIN
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'accounts:login' %}">login</a></li>  
            <li><a class="dropdown-item" href="{% url 'accounts:signup' %}">signup</a></li>
        </ul>

        {% endif %}
    </li>
</nav>