likelion_11th_B_sangjunlee_homework/likelion_11th_B_sangjunlee_homework/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likelion_11th_B_sangjunlee_homework/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('second/', secondpage, name="secondpage"),
    # app의 views.py에서 넘어옴
    # 새로 만든 views.py의 new함수와 create 함수 연결 (url만들기)
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    # mainpage.html detail부분에서 넘어옴
    # url에 post의 id 값을 넣어서 전달 -> 전달받은 id값을 통해 특정 게시글의 detail 띄우기
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name = "edit"),
    path('update/<int:id>', update, name = "update"),
    path('delete/<int:id>', delete, name = "delete"),
    path('pic_delete/<int:id>', pic_delete, name = "pic_delete"),
    path('delete_comment/<int:id>/<int:com_id>', delete_comment, name="delete_comment"),
    path('likes/<int:post_id>', likes, name="likes"),

]

likelion_11th_B_sangjunlee_homework/users/urls.py
from django.urls import path
from .views import *
app_name = "users"
urlpatterns = [
    path('mypage/<int:id>', mypage,name="mypage"),
    path('follow/<int:id>', follow, name="follow"),
]

likelion_11th_B_sangjunlee_homework/users/models.py
from django.db import models

# Create your models here.

likelion_11th_B_sangjunlee_homework/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from main.models import Post
from accounts.models import Profile
from django.contrib.auth.models import User

# Create your views here.
def mypage(request, id):

    user = get_object_or_404(User, pk=id)

    context = {
    'user':user,
    'posts':Post.objects.filter(writer=user),
    'followings':user.profile.followings.all(),
    'followers':user.profile.followers.all(),
    }
    return render(request, 'users/mypage.html', context)

def follow(request, id):
    user = request.user
    followed_user = get_object_or_404(User, pk=id)
    is_follower = user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage', followed_user.id)

likelion_11th_B_sangjunlee_homework/users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>이상준을 사랑하는 사람들의 모임</h1>

<h3>닉네임 : {{ user.profile.nickname }}</h3>
<h3>학과 : {{ user.profile.department }}</h3>
<h3>이메일 : {{ user.profile.email }}</h3>
{% if user.is_authenticated %}
    {% if request.user != user %}
        {% if request.user.profile in user.profile.followers.all %}
            <a href="{% url 'users:follow' user.id %}"><button type="button" class = "btn btn-outline-info">언팔로우</button></a>
        {% else %}
            <a href="{% url 'users:follow' user.id %}"><button type="button" class="btn btn-info">팔로우</button></a>
        {% endif %}
    {% endif %}
{% endif %}

<p>팔로워<br>{{user.profile.followers.count}}명</p>
{% for follower in user.profile.followers.all %}
    <a href="{% url 'users:mypage' follower.user.id %}">{{follower.user.username}}</a>
{% endfor %}

<p>팔로잉<br>{{user.profile.followings.count}}명</p>
{% for following in user.profile.followings.all %}
    <a href="{% url 'users:mypage' following.user.id %}">{{following.user.username}}</a>
{% endfor %}


<h2>내가 작성한 글 목록</h2>


{% endblock %}