likelion_11th_B_sangjunlee_homework/likelion_11th_B_sangjunlee_homework/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likelion_11th_B_sangjunlee_homework/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('second/', secondpage, name="secondpage"),
    # app의 views.py에서 넘어옴
    # 새로 만든 views.py의 new함수와 create 함수 연결 (url만들기)
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    # mainpage.html detail부분에서 넘어옴
    # url에 post의 id 값을 넣어서 전달 -> 전달받은 id값을 통해 특정 게시글의 detail 띄우기
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name = "edit"),
    path('update/<int:id>', update, name = "update"),
    path('delete/<int:id>', delete, name = "delete"),
    path('pic_delete/<int:id>', pic_delete, name = "pic_delete"),
    path('delete_comment/<int:id>/<int:com_id>', delete_comment, name="delete_comment"),
    path('likes/<int:post_id>', likes, name="likes"),

]

likelion_11th_B_sangjunlee_homework/users/urls.py
from django.urls import path
from .views import *
app_name = "users"
urlpatterns = [
    path('mypage/<int:id>', mypage,name="mypage"),
    path('follow/<int:id>', follow, name="follow"),
]

likelion_11th_B_sangjunlee_homework/main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# 사용할 class 생성하기

class Post(models.Model): # 모델 class 명을 Blog에서 Post로 바꾸기
    title = models.CharField(max_length=200) # title : 최대 길이 200
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE) # writer : 최대 길이 100
    mood = models.CharField(max_length=20) # mood : 기분
    weather = models.CharField(max_length=20) # weather : 오늘 날씨
    pub_date = models.DateTimeField() # pub_date : 게시날짜
    body = models.TextField() # body : post의 body
    image = models.ImageField(upload_to="post/", blank=True, null=True)
    like = models.ManyToManyField(User, related_name='likes', blank=True)
    like_count = models.PositiveIntegerField(default=0)

    
    # 이후 termianl에 python manage.py makemigrations 입력 (앱 내에 migrations 폴더를 생성해 models.py의 변경사항을 저장)
    # 아마 이시점에 python manage.py migrate 를 안했을 수도 있음. 하기.

    # Post 내용이 호출되면 데이터의 title이 '대표값'으로 나오게 함. ??? 의것의 의도 ???
    def __str__(self):
        return self.title 
    
    # 내용이 너무 많으면 앞부분만 보이도록 body의 내용 앞부분을 자르기
    def summary(self):
        return self.body[:20] #body의 20번째 인덱스까지를 리턴

class Comment(models.Model):
    content = models.TextField()
    pub_date = models.DateTimeField()
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.post.title+" : "+self.content[:20]

likelion_11th_B_sangjunlee_homework/main/views.py
from django.shortcuts import render, redirect, get_object_or_404 # Render : 템플릿을 불러옴, Redirect : URL로 이동, get_object_or_404 : 가져올 객체가 있으면 가져오고 없으면 404에러를 띄움
from .models import Post, Comment # 아깐 admin창에서 보이기 위해 불러왔다면, 여기는 views에 보여주기 위해 불러옴
from django.utils import timezone # 장고에서 제공하는 시간 관련 기능 사용
# Create your views here.
def mainpage(request):
    posts = Post.objects.all() #변수 posts에 Post의 모든 객체를 저장 즉, posts에 모든 게시물이 담긴다.
    return render(request, 'main/mainpage.html', {'posts':posts}) # mainpage.html을 띄우는 함수

def secondpage(request):
    return render(request, 'main/secondpage.html') # secondpage.html을 띄우는 함수
#=================================================================================================
def create(request):
    if request.user.is_authenticated:
        new_post = Post() # 새 Post 정의
        new_post.title = request.POST['title'] # 새 Post의 타이틀 정의 
        new_post.writer = request.user # 새 Post의 작성자 정의
        new_post.pub_date = timezone.now() # 새 Post의 시간 (작성하는 현재시간) 정의
        new_post.body = request.POST['body'] # 새 Post의 내용 정의
        new_post.mood = request.POST['mood'] # 새 Post에 내 기분 정의
        new_post.weather = request.POST['weather'] # 새 Post에 오늘 날씨 정의
        new_post.image = request.FILES.get('image')
        new_post.save()
        # 본문의 내용을 띄어쓰기로 잘라낸다.
        words = new_post.body.split(' ')
        # 만약 단어가 공백이 아니고 #로 시작하면, #를 뗀 후 tag_list에 저장한다.
        return redirect('main:detail', new_post.id)
    #로그인 안했냐 로그인하러 가라
    else:
        return redirect('accounts:login')
# new.html에서 넘어옴. new.html을 띄우는 함수
def new(request):
    return render(request, 'main/new.html') # 경로 설정, Render : 템플릿을 불러옴
#=================================================================================================
def detail(request, id):
    # id 있나 확인하고 있으면 post에 넣어서 보내주고, 없으면 404
    post = get_object_or_404(Post, pk = id)
    # ??? pk ??? : primary key. 각 객체를 구분해주는 키 값.
    if request.method =='GET':
        comments = Comment.objects.filter(post=post)
        return render(request, 'main/detail.html',{
            'post':post,
            'comments':comments,
            })
    elif request.method=="POST":
        new_comment = Comment()
        # foreignkey > blog 객체 직접 넣어주기
        new_comment.post = post
        # foreignkey > reqeust.user 직접 넣어주기
        new_comment.writer = request.user
        new_comment.content = request.POST['content']
        new_comment.pub_date = timezone.now()
        new_comment.save()
        return redirect('main:detail', id)
    return render(request, 'main/detail.html',{'post':post})
#=================================================================================================
def update(request, id):
    if request.user.is_authenticated:
        update_post = Post.objects.get(id=id)
        if request.user ==  update_post.writer:
            update_post.title = request.POST['title']
            update_post.writer = request.user
            update_post.pub_date = timezone.now()
            update_post.body = request.POST['body']
            update_post.mood = request.POST['mood'] # 새 Post에 내 기분 정의
            update_post.weather = request.POST['weather'] # 새 Post에 오늘 날씨 정의
            update_post.image = request.FILES.get('image', update_post.image)

            update_post.save()
            return redirect('main:detail', update_post.id)
    return redirect('accounts:login')

def edit(request, id):
    edit_post = Post.objects.get(id=id)
    return render(request, 'main/edit.html', {'post' : edit_post})
#=================================================================================================
def delete(request, id):
    delete_post = Post.objects.get(id=id)
    delete_post.delete()
    return redirect('main:mainpage')

def delete_comment(request, id, com_id):
    delete_com = Comment.objects.get(id = com_id)
    delete_com.delete()
    return redirect('main:detail', id)

def pic_delete(request, id):
    post_pic_delete = Post.objects.get(id=id)
    post_pic_delete.image.delete()
    return redirect('main:edit',post_pic_delete.id)
#================================================================================================
def likes(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.like.all():
        post.like.remove(request.user)
        post.like_count -= 1
        post.save()
    else:
        post.like.add(request.user)
        post.like_count += 1
        post.save()
    return redirect('main:detail', post_id)

likelion_11th_B_sangjunlee_homework/main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{post.title}}</h1>
{% if post.writer %}
<a href="{% url 'users:mypage' post.writer.id %}">작성자 : {{post.writer}}</a><br>
{% else %}
작성자 : 알 수 없음<br>
{% endif %}
날짜 : {{post.pub_date}}
기분 : {{post.mood}}
날씨 : {{post.weather}}

<a href="{% url 'main:likes' post.id %}">
    {% if user in post.like.all %}
    취소
    {% else %}
    좋아요
    {% endif %}
</a>

{{post.like_count}}개

<hr>
{% if post.image %}
    <p><img src="{{post.image.url}}" alt="사진"></p>
{% endif %}
<p>{{post.body}}</p>

{% if post.writer == user %}
<a href = "{% url 'main:edit' post.id %}">수정하기</a>
<a href = "{% url 'main:delete' post.id %}">삭제하기</a>
{% endif %}
<div class="comment_container">
    <div class="comment_form">
        <h2>댓글 작성하기</h2>
        <form method="POST" action="{% url 'main:detail' post.id %}">
            {% csrf_token %}
            <input type="text" name="content">
            <input type="submit" name="submit">
        </form>
    </div>
    <div class="comment_list">
        {% for c in comments %}
        <hr>
        <h4>작성자 : {{c.writer}}</h4>
        <p>내용 : {{c.content}}</p>
        <p>{{c.pub_date}}</p>
        {% if c.writer == user %}
        <a href = "{% url 'main:delete_comment' post.id c.id %}">삭제하기</a>
        {% endif %}
        {% endfor %}
        
    </div>
</div>
{% endblock %}

likelion_11th_B_sangjunlee_homework/main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>글 수정하기</h1>
    <form action="{% url 'main:update' post.id %}" method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <p>제목 : <input type="text" name="title" value="{{post.title}}"></p>
        <!--<p>사진 : <input type="file" name="image"></p>-->
        <p>사진 : {% if post.image %}<img src="{{ post.image.url }}" width="200" /><br />{% endif %}<input type="file" name="image"></p>
        <a href = "{% url 'main:pic_delete' post.id %}">사진 삭제하기</a>
        <p>기분 : <input type="text" name = "mood" value="{{post.mood}}"></p>
        <p>날씨 : <input type = "text" name = "weather" value="{{post.weather}}"></p>
        <p>내용 : <textarea name="body" id="" cols="30" rows="10" >{{post.body}}</textarea></p>
        <button type="submit">제출</button>
    </form>
</div>
{% endblock %}

likelion_11th_B_sangjunlee_homework/main/templates/main/mainpage.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %} 

<h1>내 사진첩</h1>
<div class="container">
    <img src = "{% static 'images/sangjunlee1.jpg' %}" style = "width : 300px;">
    <p>젊었던 이상준</p>
</div>
<div class="container">
    <img src = "{% static 'images/time table.jpg' %}" style = "width : 300px;">
    <p>이상준의 시간표</p>
</div>
<div class="container">
    <img src = "{% static 'images/이모지.png' %}" style = "width : 300px;">
    <p>이상준의 이모지</p>
</div>
<br>
{% if user.is_authenticated %}
<a href="{% url 'main:new' %}">글 쓰기</a>
{% endif %}
<h1>글 목록</h1>


<div>
    <!-- for 문을 이용해 받아온 posts에서 하나씩 띄우기, 변수 post에 하나씩 posts의 값이 들어감 -->
    {% for post in posts %}
    <div>
        <h3>{{post.title}}</h3>
        {{post.writer}}<br>
        {{post.summary}} <!-- 처음에 body였다가 summary 생성 후 일부만 보이게 함 -->
        <!-- views.py detail함수에서 넘어옴 -->
        <a href = "{%url 'main:detail' post.id %}">...자세히</a> <!-- detail 함수를 실행시키면서 post의 id값을 보내서 해당 post의 내용들을 띄우기 -->
        <br>
    </div>
    {% endfor %} <!-- for 문의 끝 -->
</div>

<!-- 
앞에서 mainpage 함수의 return에 posts라는 이름으로 Posts의 모든 객체를 보내줌
받아온 posts를 띄우면 Post 속의 모든 글들이 뜨게 되는 거다.
사전형 객체 : {key : value} value에 내용을 담고 key로 담은 내용에 접근
QuerySet : 데이터베이스에 전달받은 객체들의 모음(list) 
-->

{% endblock %}   

likelion_11th_B_sangjunlee_homework/main/templates/main/new.html
<!-- 새로운 게시물을 작성하는 템플릿 없던 녀석이니 새로 생성 -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- 위에건 중복되는 줄 base를 따른다는 뜻 -->

<form action="{%url 'main:create'%}" method="POST" enctype="multipart/form-data"> <!-- 입력값은 create url로 보내주기 -->
    <!-- 인터넷 사용자의 의지와 관계없이 공격자(해킹범)이 의도하는 행위를 웹사이트에 요청하게 만드는 공격 -->
    {%csrf_token%} 
    <!-- POST 방식 사용 시 값이 매번 변경되는 토큰을 발급해 CSRF 방어 -->
    <p>제목 : <input type = "text" name = "title"></p> 
    <p>사진 : <input type="file" name="image"></p>
    <p>기분 : <input type="text" name = "mood"></p>
    <p>날씨 : <input type = "text" name = "weather"></p>
    <p>내용 : <textarea type="text" name = "body" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

{% endblock %}
<!-- block content 부터 여기까지만 새로이 추가되는 줄 -->

likelion_11th_B_sangjunlee_homework/main/templates/main/secondpage.html
{% extends 'base.html' %} 
{% block content %} 
<h1>백엔드 3조 화이팅~~~~</h1>
<table>
    <tr>
      <th>이름</th>
      <th>직책</th>
    </tr>
    <tr>
      <td>박영신</td>
      <td>자랑스러운 멘토</td>
    </tr>
    <tr>
      <td>김윤성</td>
      <td>멋있는 멘토</td>
    </tr>
    <tr>
      <td>이상준</td>
      <td>멘티</td>
    </tr>
    <tr>
      <td>정세윤</td>
      <td>멘티</td>
    </tr>
    <tr>
      <td>최나래</td>
      <td>멘티</td>
    </tr>
    <tr>
      <td>합계</td>
      <td>5명</td>
    </tr>
  </table>
{% endblock %}   